language: node_js
node_js:
  - 4
  - 6
cache:
  directories:
    - node_modules
script:
  - npm test
#  - npm run build
#deploy:
#  provider: pages
#  skip-cleanup: true
#  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
#  keep-history: true
#  on:
#    branch: master
  